sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start dockerfile"
  - docker build -t wmc1415/docker_react -f Dockerfile.dev ./

script:
  - docker run -e CI=true wmc1415/docker_react npm run test -- --coverage


after_success:
  -echo 'success'